name: spacex_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  lottie: ^3.0.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  dartz: ^0.10.1
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  fluttertoast: ^8.2.12
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.4

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/gifs/
    - assets/icons/

